name: GitHub Snake Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Contribution Grid
        uses: platane/snk@v2
        with:
          github_user_name: mohitkumhar  # Replace with your GitHub username
          outputs: output/github-contribution-grid-snake.svg  # Path to output image or gif
